[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rock_paper_scissors_dapp = "Gdy8jkUZqJkiWc7TGuQsou8TcQP7Nay9n6Xaie4vxKGj"

[programs.devnet]
rock_paper_scissors_dapp = "Gdy8jkUZqJkiWc7TGuQsou8TcQP7Nay9n6Xaie4vxKGj"

[programs.mainnet]
rock_paper_scissors_dapp = "Gdy8jkUZqJkiWc7TGuQsou8TcQP7Nay9n6Xaie4vxKGj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
url = "https://devnet.helius-rpc.com/?api-key=4369012c-e1e4-4efb-ada7-71236d61683b"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
bind_address = "127.0.0.1"

[[test.validator.program]]
address = "73UaLSY53wiVWGURcaVJPsLQWow6mRgos88RMB5yKpY1"
path = "target/deploy/rock_paper_scissors_dapp.so"
