[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rock_paper_scissors_dapp = "G7Z1FnF9np177M8gCYhn3sudAZsoms1C8UiHhBmYNWSU"

[programs.devnet]
rock_paper_scissors_dapp = "G7Z1FnF9np177M8gCYhn3sudAZsoms1C8UiHhBmYNWSU"

[programs.mainnet]
rock_paper_scissors_dapp = "G7Z1FnF9np177M8gCYhn3sudAZsoms1C8UiHhBmYNWSU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
url = "${ANCHOR_DEPLOY_RPC}"
wallet = "~/.config/solana-secure/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
bind_address = "127.0.0.1"

[[test.validator.program]]
address = "73UaLSY53wiVWGURcaVJPsLQWow6mRgos88RMB5yKpY1"
path = "target/deploy/rock_paper_scissors_dapp.so"
